var headerElms = {
  nav_menu: ".nav-menu",
  nav_menu_login: ".nav-menu-login",
  signup_menu: "#signup-menu",
  login_menu: "#login-menu",
  dropdown_content: ".dropdown-content",
  droup_dwn_logout: "#droup_dwn_logout",
  sub_menus: ".sub_menus",
  dashboard_menus: ".div-nav-tab",
  dashboard_menusData: ".div-frame-data",
  div_profileSetting: ".div-profileSetting",
  btn_recover_pwd: "#btn_recover_pwd",
  btn_reset_pwd: "#btn_reset_pwd",
  remark: ".remark-block",
  lbl_redirect_login: ".lbl_redirect_login",
  lbl_redirect_reset_pwd: ".lbl_redirect_reset_pwd",
  lbl_redirect_register_user: ".lbl_redirect_register_user",
  btn_change_pwd: "#btn_change_pwd",
  input_id_old_password: "#id_old_password",
  input_id_new_password: "#id_new_password",
  input_id_cnfrm_password: "#id_cnfrm_password",
  lbl_error: "#lbl_error",
  btn_update_profile: "#btn_update_profile",
  img_upload_pic: "#img_upload_pic",
  input_upload_pic: "#input_upload_pic",
  upload_profile_pic: ".upload_profile_pic",
  btn_publish_advertisement: "#btn_publish_advertisement"
}