var trade = {
  "trade_type.iwant": "buy",
  "trade_type.location": "aurangabad",
  "trade_type.payment_method": "online",
  "more_information.currency": "INR",
  "more_information.margin": "5",
  "more_information.price_equation": "btc_in_usd*USD_in_USD*1.05",
  "more_information.min_trans_limit": "15000",
  "more_information.max_trans_limit": "60000",
  "more_information.opening_hours.sunday.start": "11",
  "more_information.opening_hours.sunday.end": "22",
  "more_information.opening_hours.monday.start": "11",
  "more_information.opening_hours.monday.end": "22",
  "more_information.opening_hours.tuesday.start": "11",
  "more_information.opening_hours.tuesday.end": "22",
  "more_information.opening_hours.wednesday.start": "11",
  "more_information.opening_hours.wednesday.end": "22",
  "more_information.opening_hours.thursday.start": "11",
  "more_information.opening_hours.thursday.end": "22",
  "more_information.opening_hours.friday.start": "11",
  "more_information.opening_hours.friday.end": "22",
  "more_information.opening_hours.saturday.start": "11",
  "more_information.opening_hours.saturday.end": "22",
  "more_information.terms_of_trade": "JUST trade",
  "online_selling.payment_details": "pay me",
  "online_selling.minimum_volume": "0.5",
  "online_selling.minimum_feedback": "140",
  "online_selling.new_buyer_limit": "15",
  "online_selling.transaction_volume_coefficient": "12",
  "online_selling.display_reference": "555",
  "online_selling.reference_type": "string",
  "liquidity_options.track_liquidity": "true",
  "security_options.identified_people_only": "true",
  "security_options.identify_user_before": "true",
  "security_options.real_name_required": "true",
  "security_options.sms_verification_required": "true",
  "security_options.trusted_people_only": "true",
  "user": "44444"
}
